<?= $this->form()->openTag($form) ?>

<h2 class="my-3">Koszyk:</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th><?= $form->get('typ_oferty')->getLabel() ?></th>
            <th><?= $form->get('typ_nieruchomosci')->getLabel() ?></th>
            <th><?= $form->get('numer')->getLabel() ?></th>
            <th><?= $form->get('powierzchnia')->getLabel() ?></th>
            <th><?= $form->get('cena')->getLabel() ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($oferty as $of): ?>
            <tr>
                <td><?= $of->id ?></td>
                <td><?= $of->typ_oferty ?></td>
                <td><?= $of->typ_nieruchomosci ?></td>
                <td><?= $of->numer ?></td>
                <td><?= $of->powierzchnia ?></td>
                <td><?= $of->cena ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?= $this->paginationControl(
    $oferty, 
    'sliding', 
    ['partial/paginator.phtml', 'Nieruchomosci'], 
    ['route' => 'nieruchomosci/oferty', 'parametry' => $parametry]
)
?>

<?= $this->form()->closeTag($form); ?>