<?= $this->doctype(); ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Programowanie w Internecie 1')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css')
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css')
    ?>

    <?= $this->headScript()
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js')
        ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js')
    ?>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">

            <a class="navbar-brand" href="/">Programowanie w Internecie 1</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <?= $this->navigation('navigation')
                    ->menu()
                    ->setPartial('menu')
                    ->render();
                ?>
            </div>
        </div>
    </nav>

    <div class="container">
        <?= $this->content; ?>
        <hr>
        <footer class="d-flex justify-content-between">
            <p class="text-secondary">
                Wyższa Szkoła Informatyki Stosowanej i Zarządzania
                <?= date('Y') - 1 ?>/<?= date('Y') ?>
            </p>
            <p class="text-secondary">Liczba ofert w koszyku: <strong id="liczbaOfert"><?= $this->liczba_ofert ?></strong>
            </p>
        </footer>
    </div> <!-- /container -->
    <?= $this->inlineScript() ?>
</body>

</html>